### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by mlutfy** [aghstrategies/com.aghstrategies.tsys#29]
Hi, could you tag a new official release, for the civix/PHP 8 compatibility?

Thank you!

**Comment by elisseck** [comment]
@mlutfy thanks for the push! This had been stuck behind internal review of new features (devices and civi-driven refunds). Should be all set tagged as v2.0.0

**Comment by mlutfy** [comment]
@elisseck Thanks! I updated the blog post with the version.
