### ISSUE TITLE
Request review for in-app installation

### ISSUE THREAD

**Issue by twomice** [aghstrategies/com.aghstrategies.tsys#8]
Hi @agh1 Ext-WG would love to review this and get it authorized for in-app installation. Hit us up when you're ready: https://docs.civicrm.org/dev/en/latest/extensions/publish/#automated-distribution

**Comment by alifrumin** [comment]
Hey @twomice just opened a new issue: https://lab.civicrm.org/extensions/extension-review-requests/issues/5 and closed the one I had made (https://lab.civicrm.org/extensions/extensions-directory/issues/34) using the  https://lab.civicrm.org/extensions/extensions-directory/issues/new?issue%5Btitle%5D=Request%20review%20for%20%5BFIXME_COM.FIXME_VENDOR.FIXME_NAME%5D&issue%5Bdescription%5D=/label%20%22Extension%20Review%20Request%22 link you sent me a month or so again. Thanks for reaching out!

**Comment by twomice** [comment]
Oops, was that for this extension? Thanks, @alifrumin Got it.
